spring.application.name=user-service
server.port=8081

#SPRING DATASOURCE#
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/DCPDB
spring.datasource.username=DCP_APP
spring.datasource.password=pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=10

#SPRING JPA CONFIG#
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#DEV-TOOLS CONFIG#
spring.devtools.livereload.enabled=true
spring.devtools.remote.restart.enabled=false

#JWT CONFIG#
#jwt.secret=mySecretKey12345678901234567890
jwt.secret=5367566859703373367639792F423F452848284D6251655468576D5A71347437
jwt.expiration=3600000

#LOGGING#
#logging.level.root=debug
debug=true
#logging.level.org.hibernate.stats=debug
#spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.springframework.security=DEBUG