spring.application.name=order-service

server.port=8082

#SPRING DATASOURCE#
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/DCPDB
spring.datasource.username=DCP_APP
spring.datasource.password=pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=10

#SPRING JPA CONFIG#
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#DEV-TOOLS CONFIG#
spring.devtools.livereload.enabled=true
spring.devtools.remote.restart.enabled=false

#JWT CONFIG#

#LOGGING#
#logging.level.root=debug
#debug=true
#logging.level.org.hibernate.stats=debug
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE